### ISSUE TITLE
Link not found at craigslist-renew.pl line 52

### ISSUE THREAD

**Issue by calexil** [propertone/craigslist-renew#8]
the follow_link is failing to find the link 'active'

**Comment by calexil** [comment]
dead project

**Comment by yuqianli** [comment]
how to fix this? i got this error recently. 
Thank you,

**Comment by calexil** [comment]
no idea thats why I closed it, this issue was opened in dec 2016.. the project seems abandoned

**Comment by yuqianli** [comment]
i just noticed it's not working this month..

**Comment by propertone** [comment]
I pushed out a fix - let me know if that fixes it for you.

**Comment by yuqianli** [comment]
it works. thanks a lot...
